### PR TITLE
Added :titleize filter

### PR DESCRIPTION
**Pull request by kagd**
Used [active support](http://api.rubyonrails.org/classes/ActiveSupport/Inflector.html#method-i-titleize) as a reference for this implementation.

All the string tests pass.

Also, my date tests were failing because there was no file for 0600. I added the file, although, it was never passing the tests for me. Might have been something that I was missing.

### CODE REVIEW

**Comment by kagd** [comment]
I should note that I did not generate a new readme with the `:titleize` documentation since it appears that it is generated by some system, and I am not sure which.

**Comment by kagd** [comment]
OSX 10.7.4 and jison = 0.3.2

**Comment by kagd** [comment]
Yes, all the specs passed except for the date 0600 one.

**Comment by kagd** [comment]
I will have to think about the date test a bit. I'm sure that there has to be a way to test it without having to worry about timezones.

**Comment by jeremyruppel** [comment]
This looks great though, man. Merged and published. Thanks for the help!

I know there are several Date-mocking packages out there, so I'm wondering if one of those might be useful in avoiding the travis-time-zone debacle. Anyhow, I've filed #29 for that. Thanks!

**Comment by kagd** [comment]
No problem. This is a great renderer and I am glad to give back. I will look around for some options to deal with the date testing issue.

**Pull request merged**
